### PR TITLE
I18n integration

### LINKED ISSUE #15: I18n integration
- [ ] Exception message:

```ruby
rescue_from ActionPolicy::Unauthorized do |ex|
    p ex.message #=> "You do not have access to the stage"
end
``` 
- [ ] Reasons integration:

```ruby
# when we have the reasons object
reasons.details #=> { stage: [:show?] }
# we can generate localized messages with i18n
reasons.full_messages #=> ["You do not have access to the stage"]
```

In locales:

```yml
en:
  action_policy:
    policy:
      stage:
        show?: "You do not have access to the stage"
        # default message for exceptions and reasons
    default_message: "You are not authorized to perform this action"
```

### PR DESCRIPTION
**Pull request by DmitryTsepelev**
I've tried to keep it as similar as much to the [gist](https://gist.github.com/palkan/eb6fab36c5f60e899cccacd3d5649a93) as possible. The major change is that I've added translations of the parent policies to the candidates' list.

I've also added two more Rake tasks for i18n specs, which cover the case when i18n gem is available and also when it's missing (i.e. user tries to use without requiring the gem)

Fixes #15.

### CODE REVIEW

File: lib/action_policy.rb [hunk 1]
```diff
@@ -21,6 +21,7 @@ def initialize(target)
   require "action_policy/base"
   require "action_policy/lookup_chain"
   require "action_policy/behaviour"
+  require "action_policy/i18n"
```
Comment (palkan) [inline lib/action_policy.rb]: What about requiring this file only if `I18n` is defined and avoid runtime checks?

Comment (palkan) [reply lib/action_policy.rb]: That would also allow us to run tests altogether

File: lib/action_policy/i18n.rb [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+          *policy_hierarchy.map { |klass| :"#{klass.identifier}.#{rule}" },
+          rule,
+          ::I18n.t(:unauthorized, scope: [:action_policy])
+        ]
+      end
+    end
+  end
+end
+
+I18n.load_path << Dir[File.expand_path("config/locales") + "/*.yml"] if defined?(::I18n)
```
Comment (palkan) [inline lib/action_policy/i18n.rb]: Maybe we can provide default message as a candidate?

I.e. passing `DEFAULT_UNAUTHORIZED_MESSAGE` as the last candidate.

When we add `::I18n.t(:unauthorized, scope: [:action_policy])` we assume that it's defined by the app.

File: lib/action_policy/i18n.rb [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+          candidates.shift,
+          default: candidates,
+          scope: [:action_policy, :policy]
+        )
+      end
+
+      private
+
+      def candidates_for(policy_class, rule)
+        policy_hierarchy = policy_class.ancestors.select { |klass| klass < ActionPolicy::Base }
```
Comment (palkan) [inline lib/action_policy/i18n.rb]: Calling `policy_class` is not very efficient: it could be a long list of all modules and class up to BaseObject.

See, for example, how [ActiveRecord performs lookup](https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/activerecord/lib/active_record/translation.rb#L8).

`klass < ActionPolicy::Base` – this check won't work if we do not inherit from `ActionPolicy::Base`

ActionPolicy allows to build a custom _base_ policy.

The only requirement for policy class is to include `ActionPolicy::Policy::Core` module.
We can check, for example, whether class `respond_to?(:identifier)` or not. Duck typing)

Comment (DmitryTsepelev) [reply lib/action_policy/i18n.rb]: ✔️

File: lib/action_policy/i18n.rb (hunk 2 above)
Comment (DmitryTsepelev) [reply lib/action_policy/i18n.rb]: ✔️

File: lib/action_policy.rb (hunk 1 above)
Comment (DmitryTsepelev) [reply lib/action_policy.rb]: Done. It helped for the missing i18n spec, but I still have to run i18n specs in s separate task because otherwise i18n would be required when missing spec starts running

File: lib/action_policy/policy/execution_result.rb [hunk 4]
```diff
@@ -26,6 +26,10 @@ def success?
       def fail?
         @value == false
       end
+
+      def message
+        raise I18nNotAvailableError
```
Comment (palkan) [inline lib/action_policy/policy/execution_result.rb]: We don't need to add this method stub. If there is no `i18n`, there is no method.

The same with `full_messages`

File: lib/action_policy.rb (hunk 1 above)
Comment (palkan) [reply lib/action_policy.rb]: We don't need to test the case when `i18n` is missing at all, so we can assume that's it's loaded (and load in `test_helper.rb`)

Comment (DmitryTsepelev) [reply lib/action_policy.rb]: ✔️

File: lib/action_policy/policy/execution_result.rb (hunk 4 above)
Comment (DmitryTsepelev) [reply lib/action_policy/policy/execution_result.rb]: Done. My idea was that if the user tries to call a method described in docs and gets `undefined method` he might be confused a bit.

**Comment by DmitryTsepelev** [comment]
Done and squashed everything
