### PR TITLE
Fix alias lookup

### LINKED ISSUE #18: Rule aliases in an inheriting policy don't override aliases in parent policies
### Tell us about your environment

**Ruby Version:**
2.4.3 (in Docker)

**Framework Version (Rails, whatever):**
Rails 5.2.0.rc2

**Action Policy Version:**
0.2.0

### What did you do?
```ruby
class ApplicationPolicy < ActionPolicy::Base; end

class GroupPolicy < ApplicationPolicy
  def new?
    user.staff?
  end
  alias_rule :create?, to: :new?
end
```

### What did you expect to happen?
For `GroupPolicy#create?` to be aliased to `GroupPolicy#new?`

### What actually happened?
`GroupPolicy#create?` was actually still aliased to `ActionPolicy::Base#new?` (because of the `alias_rule :create, to: :new?` in `ActionPolicy::Policy::Defaults`, I think) and so always returned false. The solution was to define another `create?` method that called `new?` explicitly.

 (Sorry, I accidentally submitted this before I'd finished it)

### PR DESCRIPTION
**Pull request by brendon**
Fixes #18

### What is the purpose of this pull request?
The rule lookup process with respect to aliases was flawed as it gave precedence to existing methods in ancestors before looking up aliases. This meant that one couldn't override an existing method on an ancestor with an alias to another method in the subclass.

### What changes did you make? (overview)
Modified the rule lookup process:
1. Look only at the methods of this class for the rule first.
2. If not found, look at the rules_aliases for a match, return matched alias target if found.
3. If not found, look at superclass (and ancestors) methods for a match.
4. If not found, look for the default rule.
5. If not found, call super to raise an error.

### Is there anything you'd like reviewers to focus on?
Coding style and perhaps oversights in logic.

PR checklist:

- [x] Tests included
- [x] Documentation updated
- [x] Changelog entry added

### CODE REVIEW

File: lib/action_policy/policy/aliases.rb [hunk 1]
```diff
@@ -29,8 +29,15 @@ def included(base)
       end
 
       def resolve_rule(activity)
-        return activity if respond_to?(activity)
-        self.class.lookup_alias(activity) || super
+        if self.class.instance_methods(false).include?(activity)
```
Comment (palkan) [inline lib/action_policy/policy/aliases.rb]: Looks a little bit complicated, especially this superclass checking. And I'm worried about the performance. A quick benchmark shows:

```ruby
require "benchmark"

GC.disable

class A
  def foo
    "foo"
  end
end

N = 1_000_000

a = A.new

Benchmark.bm(45) do |x|
  x.report("instance_methods") do
    N.times { a.class.instance_methods(false).include?(:foo) }
  end

  x.report("respond_to?") do
    N.times { a.respond_to?(:foo) }
  end
end
``` 

```
                                                  user     system      total        real
instance_methods                              0.596636   0.021402   0.618038 (  0.620872)
respond_to?                                   0.099455   0.000392   0.099847 (  0.100213)
```

**Comment by palkan** [comment]
I think, we can do the following:

- first, look up the alias if any
- second, look up the method (`respond_to?`)
- finally, fallback to default rule if any.

In order this lookup process to work we need a way to **refresh our aliases cache** when an explicit rule is specified.

And we can do that by using [`method_added` hook](https://ruby-doc.org/core-2.5.0/Module.html#method-i-method_added). Smth like:

```ruby
def method_added(name)
  rules_aliases.delete(name) if rules_aliases.key?(name)
  super
end
```

And we also need to add a good example and clarification to the docs on how aliases works (especially, defining an aliases in sub-classes and defining explicit methods in sub-classes).

**Comment by brendon** [comment]
Ok, the documentation is done now too. Hopefully that resolves everything (sorry pun).

File: lib/action_policy/policy/aliases.rb [hunk 2]
```diff
@@ -58,6 +64,10 @@ def rules_aliases
               {}
             end
         end
+
+        def method_added(name)
+          rules_aliases.delete(name) if public_method_defined?(name)
```
Comment (palkan) [inline lib/action_policy/policy/aliases.rb]: Why do we need to check for `public_method_defined?`?

Comment (brendon) [reply lib/action_policy/policy/aliases.rb]: See my other comment: https://github.com/palkan/action_policy/pull/22#issuecomment-401236630

I figured it's safer than just deleting aliases when adding private methods. I'm not sure if `public_send` goes on to the superclass to check for a public method if a public method doesn't exist on the subclass, or if it just raises?

Comment (palkan) [reply lib/action_policy/policy/aliases.rb]: >goes on to the superclass to check for a public method if a public method doesn't exist on the subclass, or if it just raises?

It raises if a private method is defined with the same name; otherwise it looks up in superclass.

Let's live the `public_method_defined?` then.

We need to add a note to the docs that only public method are considered as rules, and aliases do not affect private/protected methods.

Comment (brendon) [reply lib/action_policy/policy/aliases.rb]: Ok, that's done now :)

**Comment by palkan** [comment]
Could you please add a changelog entry with a link to the initial issue?

**Comment by brendon** [comment]
Done :)

**Comment by palkan** [comment]
Thanks!

**Comment by brendon** [comment]
Thanks @palkan :) Would you mind releasing `0.2.3`? :)

**Comment by palkan** [comment]
> Would you mind releasing 0.2.3? :)

Sure! Done.
